
variables:
    VERSION: $CI_COMMIT_TAG
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_FORCE_HTTPS: "true"
    GIT_STRATEGY: clone
    DOTNET_SDK_VERSION: "8.0"
    DOTNET_RT_VERSION: "8.0.13"   
    PROJECT_NAME: "TN_Doc"  

stages:          
  - build
  - package
  - version

get-version-job:
  stage: version
  image: mcr.microsoft.com/dotnet/sdk:${DOTNET_SDK_VERSION}
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+(\.\d+)?$/
  tags:
    - orpovy
  script:
    - CSPROJ_FILE="$PROJECT_NAME/${PROJECT_NAME}.csproj"
    - if [ ! -f "$CSPROJ_FILE" ]; then echo "Error:$CSPROJ_FILE not found"; exit 1; fi
    - VERSION=$(xmllint --xpath "//Project/PropertyGroup/Version/text()" $CSPROJ_FILE 2>/dev/null || grep -oP '<Version>\K[^<]+' $CSPROJ_FILE)
    - echo "Extracted version:$VERSION"
    - if [ -z "$VERSION" ]; then echo "Error:Version not found in $CSPROJ_FILE"; exit 1; fi
    - echo "VERSION=$VERSION" > version.env
    - echo "PROJECT_NAME=$PROJECT_NAME" >> version.env
  artifacts:
    reports:
      dotenv: version.env

build-job:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:${DOTNET_SDK_VERSION}
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+(\.\d+)?$/
  tags:
    - orpovy
  before_script:
    - mkdir -p ./publish
    - mkdir -p $PROJECT_NAME/Dll
  script:
    - echo "Adding NuGet sources..."    
    - 'dotnet nuget add source "https://nuget.ortpr.ru/v3/index.json" --name ortpr'
    - 'dotnet nuget add source "https://nuget.xn--90aia9aifhdb2cxbdg.xn--p1ai/api/v3/index.json" --name fr_nuget --username "$FR_NUGET_USERNAME" --password "$FR_NUGET_PASSWORD" --store-password-in-clear-text'
    - echo "Rebuilding solution ..."
    - dotnet build
    - echo "Moving to $PROJECT_NAME..."
    - cd $PROJECT_NAME
    - echo "Current directory after cd:$(pwd)"
    - echo "Building the application..."
    - dotnet publish ${PROJECT_NAME}.csproj -c Release -r linux-x64 --self-contained false -o ../publish
  artifacts:
    name: "build-${PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}"
    paths:
      - ./publish/

increment-build-number-job:
  stage: version
  image: mcr.microsoft.com/dotnet/sdk:${DOTNET_SDK_VERSION}
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+(\.\d+)?$/
  tags:
    - orpovy
  needs:
    - get-version-job
  cache:
    key: "${VERSION}-build-number"
    paths:
      - build_number.txt
    policy: pull-push
  script:
    - |
      if [ -f build_number.txt ]; then
        BUILD_NUMBER=$(cat build_number.txt)
        BUILD_NUMBER=$((BUILD_NUMBER+1))
        echo "Incrementing build number to: $BUILD_NUMBER"
      else
        BUILD_NUMBER=1
        echo "Starting build number: $BUILD_NUMBER"
      fi
      echo $BUILD_NUMBER > build_number.txt
    - REVISION="${CI_COMMIT_SHORT_SHA}"
    - FULL_VERSION="${VERSION}-b${BUILD_NUMBER}-${REVISION}"
    - echo "Full version:$FULL_VERSION"
    - echo "FULL_VERSION=$FULL_VERSION" > build.env
    - echo "BUILD_NUMBER=$BUILD_NUMBER" >> build.env
    - echo "REVISION=$REVISION" >> build.env
  artifacts:
    reports:
      dotenv: build.env

package-job:
  stage: package
  image: ubuntu:latest
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+(\.\d+)?$/
  needs:
    - build-job
    - get-version-job
    - increment-build-number-job
  tags:
    - orpovy
  before_script:
    - apt-get update && apt-get install -y dpkg-dev
  script:
    - echo "Packaging the application into a .deb file..."
    - DEB_NAME="$(echo "${PACKAGE_NAME}" | tr '[:upper:]' '[:lower:]' | tr '_' '.')-${VERSION}-b${BUILD_NUMBER}-${REVISION}"
    - echo "DEB_NAME=$DEB_NAME"
    - mkdir -p deb/DEBIAN
    - mkdir -p deb/opt/$PROJECT_NAME
    - mkdir -p deb/var/log/$PROJECT_NAME
    - mkdir -p deb/etc/systemd/system
    - cp -r ./publish/* deb/opt/$PROJECT_NAME/
    - |
      cat << EOF > deb/DEBIAN/control
      Package: ${PROJECT_NAME}
      Version: ${VERSION}-b${BUILD_NUMBER}
      Section: utils
      Priority: optional
      Architecture: amd64
      Depends: libgdiplus
      Maintainer: DadonovAD <dadonovad@transneft.ru>
      Description: ${PROJECT_NAME} это приложение для работы с документами СОИ СИКН/ОСИКН.
      Homepage:
      EOF
  artifacts:
    name: "package-${PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}"
    paths:
      - ./packages/
